services:
  dasharr:
    container_name: dasharr
    image: ghcr.io/frenchgithubuser/dasharr:latest
    ports:
      - "3000:80"   
    environment:
      - API_KEY=your-secure-api-key
    volumes:
      - ./config/:/backend/config/
      # dasharr needs to read your prowlarr database to use your indexers' credentials
      - /absolute/path/to/prowlarr/volume/config/prowlarr.db:/backend/prowlarr/prowlarr.db:ro

