services:
  dasharr:
    container_name: dasharr
    image: ghcr.io/frenchgithubuser/dasharr:latest
    ports:
      # frontend interface
      - "3000:80"   
      # api port
      - "1323:1323" 
    environment:
      - API_KEY=your-secure-api-key
    volumes:
      - ./database/:/backend/config/database/
      # dasharr needs to read your prowlarr database to use your indexers' credentials
      - /absolute/path/to/prowlarr/volume/config/prowlarr.db:/backend/prowlarr/prowlarr.db:ro

